---
title: "Concentration-Discharge Relationships"
author: "Taryn Waite"
date: "6/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpubr)
source("C_Q_plotting_functions.R")
```

```{r}
subset <- WQ_hourly_discharge %>% 
    filter(date >= ymd("2017-05-18") & date <= ymd("2017-06-09")) %>% 
    filter(site == "MC")

a <- subset %>%  
      ggplot(aes(x = dateTime, y = hourlyDischarge)) +
      geom_line() +
      xlab("Time") +
      ylab("Discharge (ft^3/s)")

b <-  subset %>%  
      ggplot(aes(x = dateTime, y = Turb)) +
      geom_line() +
      xlab("Time") +
      ylab(y_axis_label("Turb"))

c <-  subset %>%  
    ggplot(aes(x = hourlyDischarge, y = Turb)) +
    geom_path() 
    
     # put all 3 plots together
  
    figure <- ggarrange(a, b, c)
    figure
```


```{r multi variable C-Q plotting function}
# plots C-Q relationships for up to 4 variables
# specify start date and end date
# optionally specify which site to plot (otherwise, both will be included in each plot)
multi_var_CQ <- function (var1, var2 = NA, var3 = NA, var4 = NA, startDate, endDate, site1 = NA){
  # subset the data between the given start and end dates
  subset <- WQ_hourly_discharge %>% 
    filter(date >= ymd(startDate) & date <= ymd(endDate)) %>% 
    arrange(dateTime)
  # subset to the given site if it's provided
  if(!is.na(site1)){
    subset <- subset %>% 
      filter(site == site1)
  }
  
  # find the peak discharge for the storm
  peak <- subset %>% filter(hourlyDischarge == max(hourlyDischarge)) 
  peakDateTime <- peak[["dateTime"]]
  
  # classify each observation as rising limb or falling limb
  subset <- subset %>% 
    mutate(limb = case_when(dateTime <= peakDateTime ~ "RL", T ~ "FL"))
  
  
  # plot the first variable
  a <-  subset %>%  
    ggplot(aes_string(x = "hourlyDischarge", y = var1, 
                      col = case_when(!is.na(site1) ~ "limb", T ~ "site"))) +
    geom_path() +
    # start points
      geom_point(data = subset[subset$site == "MC",][1,], 
                aes_string("hourlyDischarge", y = var1), col = "black") +
      geom_point(data = subset[subset$site == "SI",][1,], 
                aes_string("hourlyDischarge", y = var1), col = "black") +
      theme(legend.position = "none") +
      xlab ("Discharge") + ylab(y_axis_label(var1)) 
  
  
  figure <- a
  
  # plot the second variable if it's given
  if(!is.na(var2)){
    b <-  subset %>%  
    ggplot(aes_string(x = "hourlyDischarge", y = var2, 
                      col = case_when(!is.na(site1) ~ "limb", T ~ "site"))) +
    geom_path() +
    # start points
      geom_point(data = subset[subset$site == "MC",][1,], 
                aes_string("hourlyDischarge", y = var2), col = "black") +
      geom_point(data = subset[subset$site == "SI",][1,], 
                aes_string("hourlyDischarge", y = var2), col = "black") +
      theme(legend.position = "none") +
      xlab ("Discharge") + ylab(y_axis_label(var2)) 
    
    figure <- ggarrange(a, b)
  }
  
  # plot the third variable if it's given
  if(!is.na(var3)){
    c <-  subset %>%  
    ggplot(aes_string(x = "hourlyDischarge", y = var3, 
                      col = case_when(!is.na(site1) ~ "limb", T ~ "site"))) +
    geom_path() +
    # start points
      geom_point(data = subset[subset$site == "MC",][1,], 
                aes_string("hourlyDischarge", y = var3), col = "black") +
      geom_point(data = subset[subset$site == "SI",][1,], 
                aes_string("hourlyDischarge", y = var3), col = "black") +
      theme(legend.position = "none") +
      xlab ("Discharge") + ylab(y_axis_label(var3)) 
    
    figure <- ggarrange(a, b, c)
  }
  
  # plot the fourth variable if it's given
  if(!is.na(var4)){
    d <-  subset %>%  
    ggplot(aes_string(x = "hourlyDischarge", y = var4, 
                      col = case_when(!is.na(site1) ~ "limb", T ~ "site"))) +
    geom_path() +
    # start points
      geom_point(data = subset[subset$site == "MC",][1,], 
                aes_string("hourlyDischarge", y = var4), col = "black") +
      geom_point(data = subset[subset$site == "SI",][1,], 
                aes_string("hourlyDischarge", y = var4), col = "black") +
      theme(legend.position = "none") +
      xlab ("Discharge") + ylab(y_axis_label(var4)) 
    
    figure <- ggarrange(a, b, c, d)
  }
  # show the figure
  figure
}
```

Here are some examples of how we can use the multi-variable C-Q plotting function to compare the C-Q relationships for turbulence, nitrate, chlorophyll, and dissolved organic matter:
```{r examples}
## C-Q plots for a storm, just MC site
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-07-13", "2016-08-10", site1 = "MC")
## C-Q plots for the same storm, just SI site
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-07-13", "2016-08-10", site1 = "SI")
## C-Q plots for the same storm, both sites
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-07-13", "2016-08-10")


## C-Q plots for some other storms, just MC site

# ================================ 2015 =====================================

#SI problem
WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2015-09-03 12:05:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2015-09-03 12:05:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2015-09-03 12:05:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2015-09-03 12:05:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2015-09-03 12:05:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2015-09-03 12:05:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2015-09-03 12:05:00")))

multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2015-07-06", "2015-07-28", site1 = "MC")
#multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             #"2015-08-05", "2015-08-17", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2015-08-18", "2015-09-04", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2015-09-09", "2015-09-17", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2015-09-17", "2015-09-24", site1 = "MC")
#multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             #"2015-10-05", "2015-10-19", site1 = "MC")

# ================================ 2016 =====================================

# deal with some single missing data rows for 20166 events 
reassign<- function (data, var, DateTime){
  t<-((data[which(data$dateTime==ymd_hms(DateTime) - 7200), var]+
         data[which(data$dateTime==ymd_hms(DateTime) + 7200), var])/2)
  return(as.numeric(t))
}
WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2016-05-16 10:34:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2016-05-16 10:34:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2016-05-16 10:34:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2016-05-16 10:34:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2016-05-16 10:34:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2016-05-16 10:34:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2016-05-16 10:34:00")))

WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2016-10-11 10:49:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2016-10-11 10:49:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2016-10-11 10:49:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2016-10-11 10:49:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2016-10-11 10:49:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2016-10-11 10:49:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2016-10-11 10:49:00")))

# SI problem
WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2016-08-18 13:28:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2016-08-18 13:28:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2016-08-18 13:28:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2016-08-18 13:28:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2016-08-18 13:28:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2016-08-18 13:28:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2016-08-16 23:28:00")))
WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2016-08-16 23:28:00")),] %<>%
  mutate(Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2016-08-16 23:28:00")))

multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-04-25", "2016-05-24", site1 = "MC")


# missing data below
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-05-28", "2016-07-11", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-06-01", "2016-06-14", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-07-13", "2016-08-10", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-08-10", "2016-09-05", site1 = "SI")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-09-06", "2016-09-20", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2016-09-20", "2016-10-15", site1 = "MC")

# ================================ 2017 =====================================
WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2017-09-12 13:13:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2017-09-12 13:13:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2017-09-12 13:13:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2017-09-12 13:13:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2017-09-12 13:13:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2017-09-12 13:13:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2017-09-12 13:13:00")))


multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-06-14", "2017-06-28", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-07-19", "2017-07-25", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-07-26", "2017-07-30", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-08-06", "2017-08-13", site1 = "MC")
#multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             #"2017-08-13", "2017-09-17", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-08-16", "2017-09-17", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-09-20", "2017-09-24", site1 = "MC")
# below has many missing values
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2017-10-05", "2017-10-31", site1 = "MC")

# ================================ 2018 =====================================

WQ_hourly_discharge[which(WQ_hourly_discharge$dateTime==ymd_hms("2018-09-06 11:47:00")),] %<>%
  mutate(NO3_mgL = reassign(WQ_hourly_discharge, "NO3_mgL", ymd_hms("2018-09-06 11:47:00")),
         Turb = reassign(WQ_hourly_discharge, "Turb", ymd_hms("2018-09-06 11:47:00")),
         CHLugL = reassign(WQ_hourly_discharge, "CHLugL", ymd_hms("2018-09-06 11:47:00")),
         FDOMqsu = reassign(WQ_hourly_discharge, "FDOMqsu", ymd_hms("2018-09-06 11:47:00")),
         BGAugL = reassign(WQ_hourly_discharge, "BGAugL", ymd_hms("2018-09-06 11:47:00")),
         Temp = reassign(WQ_hourly_discharge, "Temp", ymd_hms("2018-09-06 11:47:00")))

multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2018-06-15", "2018-07-31", site1 = "MC")
multi_var_CQ(var1 = "Turb", var2 = "NO3_mgL", var3 = "CHLugL", var4 = "FDOMqsu",
             "2018-09-03", "2018-09-15", site1 = "MC")




```

```{r}

a <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2015-07-06", endDate = "2015-07-28", site1 = "MC")
#multi_var_CQ(var1 = "NO3_mgL", startDate = "2015-08-17", endDate = "2015-09-04", site1 = "MC")
b <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2016-06-01", endDate = "2016-06-14", site1 = "MC")
c <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2016-07-13", endDate = "2016-08-10", site1 = "MC")
d <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2016-08-10", endDate = "2016-09-05", site1 = "MC")
e <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2016-09-06", endDate = "2016-09-20", site1 = "MC")
f <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2016-09-20", endDate = "2016-10-15", site1 = "MC")
g <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2017-07-19", endDate = "2017-07-25", site1 = "MC")
h <- multi_var_CQ(var1 = "NO3_mgL", startDate = "2018-06-15", endDate = "2018-07-31", site1 = "MC")
#multi_var_CQ(var1 = "NO3_mgL", startDate = "2018-09-03", endDate = "2018-09-15", site1 = "MC")

ggarrange(a, b, c, d)
ggarrange(e, f, g, h)

z <- multi_var_CQ(var1 = "Turb", startDate = "2016-07-13", endDate = "2016-08-10", site1 = "MC")

ggarrange(b, z)
```

```{r}
varNames <- c("BGAugL", "CHLugL", "FDOMqsu", "NO3_mgL", "Turb")
eventDatesMC <- matrix(c("2016-04-25-00-00", "2016-05-24-23-59",
                         "2016-07-13-00-00", "2016-08-10-23-59",
                         "2016-06-01-00-00", "2016-06-14-23-59",
                         "2016-08-10-00-00", "2016-09-05-23-59",
                         "2016-09-06-00-00", "2016-09-20-23-59",
                         "2016-09-20-00-00", "2016-10-15-23-59",
                         "2015-07-06-00-00", "2015-07-28-23-59",
                         "2017-06-14-00-00", "2017-06-28-23-59",
                         "2017-07-19-00-00", "2017-07-25-23-59",
                         "2017-07-26-00-00", "2017-07-30-23-59",
                         "2017-08-06-00-00", "2017-08-13-23-59",
                         "2017-09-20-00-00", "2017-09-24-23-59",
                         "2017-08-16-00-00", "2017-09-17-23-59",
                         "2015-09-17-00-00", "2015-09-24-23-59",
                         "2015-09-09-00-00", "2015-09-17-23-59",
                         "2018-06-15-00-00", "2018-07-31-23-59",
                         "2018-09-03-00-00", "2018-09-15-23-59",
                         "2015-08-18-00-00", "2015-09-04-23-59"), 
                       nrow = 18, ncol = 2, byrow = T)
figs <- list()
for(d in 1:18){
  figs[[d]] <- list()
  start <- eventDatesMC[d,1]
  end <- eventDatesMC[d,2]
  for(i in 1:5){
    tryCatch(
    {y <- trend.cq.df(WQ_hourly_discharge, "MC", varNames[i],
                         start, end, 12)
    figs[[d]][[i]] <- plot.smooth.cq(y, varNames[i])},
    error = function(cond){
      df <- data.frame()
      figs[[d]][[i]] <- ggplot(df) + geom_point() + xlim(0, 10) + ylim(0, 100)
    }
    )
  }
}

for(d in 1:18){
  png(filename = paste0("MC_events/", eventDatesMC[d,1], ".png"), width = 6, height = 4, 
      units = "in", res = 300)
  print(ggarrange(figs[[d]][[1]], figs[[d]][[2]], figs[[d]][[3]], figs[[d]][[4]], figs[[d]][[5]]))
  dev.off()
}
```

